# Originally from https://www.jameswright.xyz/post/deploy-hugo-academic-using-githubio/
# Using the action https://github.com/benmatselby/hugo-deploy-gh-pages
# Now from https://github.com/peaceiris/actions-hugo

name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout master
      uses: actions/checkout@v4
    
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.120.3'
        extended: true

    - name: Build
      run: hugo --minify

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.TOKEN }}
        external_repository: ghurault/ghurault.github.io
        publish_dir: ./public
        publish_branch: master
