# From https://www.jameswright.xyz/post/deploy-hugo-academic-using-githubio/

name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Hugo Deploy GitHub Pages
      uses: benmatselby/hugo-deploy-gh-pages@master
      env:
        HUGO_VERSION: 0.68.3
        TARGET_REPO: ghurault/ghurault.github.io
        TOKEN: ${{ secrets.TOKEN }}
        CNAME: ghurault.github.io
